=pod

=head1 NAME

prf - Perl refactoring toolkit

=head2 Inspect class

Prints class' information (package name, isa, methods, inherited methods etc).

    prf inspect /path/to/modules Foo::Bar::Baz

    Package:
      Foo::Bar::Baz
    Methods:
      new (Main)
      bar
    Protected methods:
      _hello

=head2 List classes

Prints classes with its parents.

    prf class_list /path/to/modules

    Foo::Bar::Baz
    Main < Foo::Bar::Baz

=head2 ISA tree

Prints classes with its children.

    prf isa_tree /path/to/modules

    Foo::Bar::Baz
     + Main

=head2 Rename a module

Move the package removing left empty directories, rename the package, find and
replace all occurencies of this module (including inheritance via C<base> and
C<parent>, C<use> and method invokations).

    prf rename_module Foo::Bar::Baz Hi::There

=cut
